"""initial schema

Revision ID: 89cfa030ff7e
Revises: 
Create Date: 2026-08-19 20:15:48.202440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('proxy', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('viewport', sa.String(), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('warmup_stage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('locked_task_ref', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("purpose IN ('parsing','messaging','both')", name='ck_accounts_purpose'),
    sa.CheckConstraint("status IN ('active','flood','banned','cooldown','locked')", name='ck_accounts_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index('ix_accounts_status_platform_purpose', 'accounts', ['status', 'platform', 'purpose'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('draft','running','paused','completed')", name='ck_campaigns_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('group_url', sa.String(), nullable=False),
    sa.Column('admin_contact', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('new','queued','contacted','replied','rejected')", name='ck_leads_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_leads_platform_external_id')
    )
    op.create_index('ix_leads_status_platform_campaign', 'leads', ['status', 'platform', 'campaign_id'], unique=False)
    op.create_table('sessions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('storage_state_enc', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('messages',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('template_variant', sa.String(), nullable=True),
    sa.Column('text_sent', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('reply_status', sa.String(), server_default='none', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("delivery_status IN ('sent','failed','pending')", name='ck_messages_delivery_status'),
    sa.CheckConstraint("reply_status IN ('none','replied','no_reply')", name='ck_messages_reply_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_account_sent_at', 'messages', ['account_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###

    # campaigns.template_id <-> templates.campaign_id form a logical cycle; both tables
    # already exist above without these FKs, added here explicitly so order doesn't matter.
    op.create_foreign_key(
        'fk_campaigns_template_id_templates',
        'campaigns', 'templates',
        ['template_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_templates_campaign_id_campaigns',
        'templates', 'campaigns',
        ['campaign_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    # Drop the cross-table FKs first — they must go before either table is dropped.
    op.drop_constraint('fk_templates_campaign_id_campaigns', 'templates', type_='foreignkey')
    op.drop_constraint('fk_campaigns_template_id_templates', 'campaigns', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_account_sent_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_index('ix_leads_status_platform_campaign', table_name='leads')
    op.drop_table('leads')
    op.drop_table('templates')
    op.drop_table('campaigns')
    op.drop_index('ix_accounts_status_platform_purpose', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
